apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-user-password
  namespace: default
spec:
  encryptedData:
    password: AgBMFOJnYTrFEJqhSh7pcCDGOotcpxpXEX5S9g5aAAnk7c8ZKXB5UkPTehYmM8QmPQCtgmbNsDYxAtmvHImj2MZq0GlOGv6ETvWdHkmYV9mNArD4U/oBQhHvEyaNYDDhvb0Epz3on7F7hozcOopM4QJB8UWOI/18rmbddDRtSkjpwLc2ISE6XhFuEh39ndMSHhS+SNdzGKIINsIghzT/bRPwPwC10o2mXNu8MOtqLWQAKuz1h4+1y9u4jj7URbQBD1ZtoKZNVIPGztPcs5Ye4GZjkFD2zFgBNWK4KEO+Fd+CzLp+Qjb7Dq95Fl+fFJ3tCD5pdziofrbmpRLp5c+d1/LJUfM5ygPFabW9KctUlX0Xy5yvgtlXRnMEyAEk9o2n4HWfkJKRy9AIg/NDMqA6G0+30EDCtTBXHX/7paB8B/G1AIXfwFKfaRT14mdJYYcHTzbMpqflcExkOKVEwQ9UDjma6WXz8C8nG9DKxIaYauUBV5t3RRDe/aqQVdZVuIksDZAtcg3YLlBwOTd3LujVfF7aanngB0ka9zp7D0I0N82BAQjEuEyek4v3ioXreKpSbemRX+VtX+Ao2W2LdPz8jI6viXFvmcQvB7iUUzK+fQQEtT3quoG1rvFBOOLVln9jb6FTbng6rcgVHMEi9721nqgndNhYphn7LQ3nDFyJb0lRcMWakUUqAfy61PAqTNE0rl1D1Dsm5bLvQzFAtQ==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-user-password
      namespace: default
