apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    chart: jenkins
    repoURL: "https://charts.jenkins.io"
    targetRevision: 5.8.110
    helm:
      releaseName: jenkins
      values: |
        controller:
          serviceType: NodePort
          servicePort: 8080
          nodePort: 32000
          jnlpPort: 50000
          adminUser: admin
          adminPassword: admin
  destination:
    server: "https://kubernetes.default.svc"
    namespace: jenkins-ns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
