apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata: 
  name: petcline
  namespace: argocd
spec: 
  project: default 
  source: 
    repoURL: 'https://github.com/nhahub/NHA-255.git'
    path: manifests 
    targetRevision: CD/Argocd
  destination: 
    server: 'https://kubernates.default.svc'
    namespace: default
  syncPolicy: 
    automated:
      selfHeal: true
      prune: true 
